### ISSUE TITLE
Remove dependency on github.com/deis/pkg/time

### ISSUE THREAD

**Issue by arschles** [deis/controller-sdk-go#4]
I believe `github.com/deis/pkg/time` is only used in one place - for time formatting between the server and the client. However, this package comes with dependencies on `k8s.io/kubernetes/pkg/...`, which is huge. This issue is for removing the dependency altogether, so that we don't have to pull in a 100MB+ (iirc) dependency to get 1 constant

**Comment by bacongobbler** [comment]
> I believe github.com/deis/pkg/time is only used in one place - for time formatting between the server and the client.

you are correct, sir. :tophat:

**Comment by Joshua-Anderson** [comment]
I'll take a look into this after I finish migrating the CLI to use the SDK!

**Comment by Joshua-Anderson** [comment]
It seems like the best short term fix is to copy it into the sdk, so I did that in #8
